### PR TITLE
Add new properties 

### PR DESCRIPTION
**Pull request by feleko**
Hello,

I added new properties for Toast.

* hideCloseIcon
* iconSize

### CODE REVIEW

**Comment by artkow** [comment]
+1

**Review by jeanverster — APPROVED** [review]
This looks good 👍🏼 Apologies for only reviewing now

**Comment by feleko** [comment]
Thanks

**Comment by kdo1234** [comment]
Would it be a good idea to publish a new npm with these changes? Thank you

**Pull request merged**
